name: Ubuntu
on: 
  push:
    paths-ignore:
      - '*.md'
      - '*.bat'
      - '*.sh'
      - 'LICENSE'
      - '.clang-format'
      - '.gitignore'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.bat'
      - '*.sh'
      - 'LICENSE'
      - '.clang-format'
      - '.gitignore'
      - 'doc/**'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        qt_ver: [5.12.6]
        qt_arch: [gcc_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          version: ${{ matrix.qt_ver }}
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev libfontconfig1-dev
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
            python-version: '2.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
            architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: build ubuntu
        run: |
          chmod a+x syncSkia.sh
          ./syncSkia.sh
          qmake "CONFIG+=release"
          make
